// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCOS.API.Data;

namespace SCOS.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SCOS.API.Models.DadosSensor", b =>
                {
                    b.Property<int>("IdDadosSensor")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataEnvio");

                    b.Property<string>("Temperatura");

                    b.Property<string>("Umidade");

                    b.HasKey("IdDadosSensor");

                    b.ToTable("DadosSensor");
                });

            modelBuilder.Entity("SCOS.API.Models.Produto", b =>
                {
                    b.Property<string>("CodigoBarras")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<double>("Preco");

                    b.HasKey("CodigoBarras");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("SCOS.API.Models.Usuario", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChaveAcesso");

                    b.HasKey("ID");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
